### ISSUE TITLE
Keyword error

### ISSUE THREAD

**Issue by remyx11** [chlec/Cop-It#15]
No matter what i try, i keep getting that the keywords not match the products. Even when i fill in the entire name of the article, it won't work.

**Comment by Phalap** [comment]
I have the same problem.
Supreme must have changed their source.

**Comment by GEKTHEBOSS** [comment]
True! The Instant Buy Button saved me tho!

**Comment by carl1to** [comment]
Actually works on EU store. Are you on US?

**Comment by GEKTHEBOSS** [comment]
Actually it didnt work for piss tee in EU, had to get it with Instant Buy, check e-mail i sent you screenshot

**Comment by carl1to** [comment]
I saw your e-mail. Which keywords did you use? If you see "No item found....", there are two reasons. The first is keywords are incorrect, and second is sold-out item. Are you sure the item wasn't soldout when you start the bot?

**Comment by GEKTHEBOSS** [comment]
Yeah i started it automatically at 12:00:00 like always with refresh on drop, it clearly said Piss keyword not found and it was available as i bought it some seconds later clicking the Instant Buy button

**Comment by remyx11** [comment]
Yup, used the same keywords. Got the error as well. What is the "instant buy" @GEKTHEBOSS?

**Comment by PhungMaster** [comment]
I had this problem to. I tried to cop the Hooded Logo Half Zip and it didn't even work

**Comment by chlec** [comment]
Now fixed.
