### ISSUE TITLE
Problem with keywords

### ISSUE THREAD

**Issue by alexgiorgetti** [chlec/Cop-It#21]
Hi, i have tried two week to buy , first "Arabic Logo Hoodied" and second "Supreme/Nike collab" but the keywords of these products did not work

**Comment by carl1to** [comment]
Hey,

Had you set "Arabic Logo Hoodied" and second "Supreme/Nike collab" in keywords fileds?

**Comment by alexgiorgetti** [comment]
No, i use , arabic or logo or for the nike collab "trail" but with both does not go, try it with the nike collab
