### ISSUE TITLE
cvc isnt auto filled

### ISSUE THREAD

**Issue by ayStars** [chlec/Cop-It#24]
does not work. have to manually put on on new supreme checkout

**Comment by gerry02** [comment]
open the code of the supreme.js file and fix the code with `$("#vval").val(r.cvv);`

**Comment by adrichman** [comment]
i've prepared a pull request for selectors that would hopefully be more robust:
https://github.com/carl1to/Cop-It-Supreme-Bot/pull/27

**Comment by chlec** [comment]
Works now on the 2.0
