### ISSUE TITLE
Dropdowns dont update the selected value

### ISSUE THREAD

**Issue by KniveKc** [chlec/Cop-It#28]
On the checkout page : 
$('#credit_card_type').val('paypal')

changes the value of the Credit Card Type field to "PayPal" but doesnt update it, the PayPal Logo wont show, and on submit an error is shown stating that cc info is missing.

using the chrome console with the $('#credit_card_type').val('paypal').change() command will update it perfectly and allows the redirect to paypal.com

Using that line of code in the supreme.js , does not solve the problem somehow.

**Comment by chlec** [comment]
I totally re-code the extension, I can't help you now so. But it should be easy to set up
