### ISSUE TITLE
Chrome Error Message

### ISSUE THREAD

**Issue by xdmod2** [chlec/Cop-It#29]
"This extension may have been corrupted". I can enable it at all

**Comment by trotelvonnebenan** [comment]
Found a workarround!

**Comment by stcalica** [comment]
How are you installing it?
Put Chrome > chrome://extensions > Developer Mode
Unzip the crx extension
chrome://extensions > Load Unpacked Extension

**Comment by chlec** [comment]
Should work know. Please check the README.
