### ISSUE TITLE
Doesn't launch

### ISSUE THREAD

**Issue by jericho35** [chlec/Cop-It#35]
Salut il est impossible de cliquer sur les boutons starts et Cop on Restock doit on attendre que tu lance le serveur de ton coté pour y avoir accès? j'utilisais deja la V1 donc ça va il est pas plus dur à remplir^^

**Comment by chlec** [comment]
Salut,

Le serveur est toujours lancé en continu. Tu as bien remplis keywords + sélectionné les bonnes options + tes infos de paiements ? Vérifie bien quand même avant.

**Comment by jericho35** [comment]
les infos de paiement sont obligatoire pour que le bot se lance ? avant c'était une option

**Comment by jericho35** [comment]
effectivement les infos de paiement ne sont pas en option c'est un peu bizarre ahah je vais donc mettre des fausses information je favorise paypal pour mes paiements

**Comment by chlec** [comment]
Ah ouais j'avais pas pensé a ça, je mettrai à jour bientot

**Comment by jericho35** [comment]
pas de soucis :) merci encore pour les infos :)

**Comment by jericho35** [comment]
de plus on ne peut pas faire en sorte que si la taille choisit n'est plus dispo il tente la prochaine

**Comment by chlec** [comment]
Tu peux choisir l'odre des tailles que tu veux, tu as juste a cliquer sur plusieurs tailles et tu vois un petit numéro qui montre l'ordre

**Comment by jericho35** [comment]
ah ouais ! Très bonne idée cette feature
