### ISSUE TITLE
Shoe sizes (US and UK) doesn't match

### ISSUE THREAD

**Issue by Phalap** [chlec/Cop-It#36]
As the title suggest, the sizes are not correct.

For example:

A US10 is normally a UK9,5
But on Cop-It, it suggest that a US10 is same size as a UK9

Liking the new update a lot though!

**Comment by chlec** [comment]
Last year on Supreme x Nike x CDG shoes sizes were like "US10 - UK9", do they change that?

**Comment by Phalap** [comment]
Didn't realise that. Guess we will have to wait and see. :-)

**Comment by Phalap** [comment]
@chlec 
You were right.
US 10 / UK 9
