### ISSUE TITLE
Japan bug

### ISSUE THREAD

**Issue by rah-ool** [chlec/Cop-It#42]
There seems to be an issue with Japan support. The user cannot save their shipping information and the bot freezes at "Copping item."

**Comment by chlec** [comment]
For saving shipping info this is the same way than EU and US. Do you have an error?

Can you tell me which keywords did you use and when the bot freeze? Thank you

**Comment by rah-ool** [comment]
Yes. I used Japan as my region and tried to checkout several items that were in stock (i.e. keywords: "Hanes tag-less", color: "black", size: "medium"). No matter what item I enter, the bot stays on the "Copping item ..." screen. I got the browser to say "saved shipping information" again by fixing the numbers in the following lines in settings.js:
`else if (localStorage.store === "us") {
				$(".form-group").eq(9).css("display", "none"); //address 3 input
				$(".form-group").eq(12).css("display", "block"); //state input
				requiredShipping.push("state");
			} else if (localStorage.store === "jpn") {
				$(".form-group").eq(8).css("display", "none"); //address 3 input
				$(".form-group").eq(7).css("display", "none"); //address 2 input
				$(".form-group").eq(13).css("display", "none"); //country input
				$(".form-group").eq(12).css("display", "block"); //state input
				requiredShipping.push("state");
				requiredShipping.splice("country", 1)
`
The issue is that the bot no longer adds products to the cart like it does for the other countries.

**Comment by chlec** [comment]
I tried with a VPN in Singapore (Supreme redirects me to the Japan store) last week. Maybe they updated the store, I'll check this asap.

**Comment by chlec** [comment]
Should be fixed. Please reopen if not.

**Comment by rah-ool** [comment]
I'm getting the same error. Here is a video: https://im2.ezgif.com/tmp/ezgif-2-a28ebeaeaa.gif
