### ISSUE TITLE
Japan bug

### ISSUE THREAD

**Issue by rah-ool** [chlec/Cop-It#43]
Re-opening #42. Here's a video of the issue: https://im2.ezgif.com/tmp/ezgif-2-a28ebeaeaa.gif

### Fixed from last time
Cart now shows up and add-to-cart button is clickable

### Still an issue
Bot does not take user to checkout screen and stays on the page "Copping item" even if item is in stock.

**Comment by chlec** [comment]
It works nice for me with the same params. Had you updated the extension? Which features did you use?

**Comment by rah-ool** [comment]
Still no luck. All updated and even tried using the repo itself. Here's a video with all my settings properly configured: https://im2.ezgif.com/tmp/ezgif-2-62847b306a.gif

There seems to be some kind of issue with the Japan site because it adds to item to cart in the background but still does not take the user to the checkout screen like it does for the UK and US regions.

**Comment by rah-ool** [comment]
Solved. Issue was bad VPN.
