### ISSUE TITLE
Local new Drop Check

### ISSUE THREAD

**Issue by elypt** [chlec/Cop-It#44]
Please implement something to check if there is a new drop, without a connection to your Server. It doesn't really work and I think it's easier to have it local.

**Comment by chlec** [comment]
Hi, it's work nice if you start before the drop. I'll make this if you want but you can probably get a card declined because you'll load the supreme page many times

**Comment by elypt** [comment]
I tried it today, but it got stucked. Which Interval do you use on your Server to load the Supreme Website and which for the Bot to check if the JSON is updated? Maybe make this a little bit faster. Have you tested it today? Maybe you can show your Settings.

**Comment by chlec** [comment]
Not tested today but works on all previous drop.

It checks every 350ms, I'll check this asap.

**Comment by chlec** [comment]
Server is now fixed. I added a timeout now. Will work to add this locally soon.
