### ISSUE TITLE
Waiting for new drop...

### ISSUE THREAD

**Issue by maximvanneste** [chlec/Cop-It#45]
Hi,

I used the bot today  and I launched it like 20 seconds before the drop with these features enabled:
https://imgur.com/a/CxBvg

The bot didn't cop any item and it was stuck on 'waiting for new drop' while I copped the item manually on my laptop (the bot was still stuck on waiting for new drop...) on the desktop.

**Comment by jasunbourne** [comment]
It looks like the websocket the bot uses to check when theres a new drop is down

**Comment by chlec** [comment]
Same issue than #44, I'll fix it soon.
