### ISSUE TITLE
Agree to Terms & Checkout 

### ISSUE THREAD

**Issue by Dancull47** [chlec/Cop-It#46]
Could you please enable Agreeing to Terms of Service and fully checkout?

**Comment by Dancull47** [comment]
I'm currently on US Supreme New York. When I have the "Auto-Submit Checkout Page (not coded yet)" enabled, it still doesn't do anything.

I understand it's not yet coded, but that's what I'm requesting along with the Agree to Terms.

**Comment by chlec** [comment]
Oh crap, I had implement this but I haven't remove the "(not coded yet)" part.

It's now fixed, they also have updated their checkbox.
