### ISSUE TITLE
Load Unsafe Scripts Terms of Service

### ISSUE THREAD

**Issue by Dancull47** [chlec/Cop-It#48]
Hey Chlec, I opened an issue last week about the Bot not agreeing to the Terms of Service and checking out, but now I found the reason why.

It requires me to "Load Unsafe Scripts" in order for it to agree to terms and checkout.

**Comment by chlec** [comment]
This is weird, I updated the bot since and it seem to works. The reason was supreme updated their checkout form on the US store.

Does it work for you now?
