### ISSUE TITLE
japan

### ISSUE THREAD

**Issue by nqarubik** [chlec/Cop-It#8]
-Can you add japan store?
-Supreme japan allows Cash On Delivery, Please add it
thanks you

**Comment by carl1to** [comment]
Hey.

I'm on exams now until the end of september, I can't develop this for the moment. But no probleme when I'll be back.

**Comment by nqarubik** [comment]
Ok thanks you <3

**Comment by chlec** [comment]
Sorry for delay, I'm now back on this project. I will check how to add japan soon.

**Comment by chlec** [comment]
Japan now supported! Did some tests and seem works. Please open an issue if you find some bugs.
